project:
  type: website
  output-dir: docs

website:
  title: "MNCN-CSIC 2026 - LLM tools for R"
  navbar:
    background: "#01497c"
    pinned: true
    align: left
    left: 
      - href: materials.qmd
        text: Course materials
  page-footer:
    left: "Built with [Quarto](https://quarto.org/)."
    right: "Luis D. Verde Arregoitia - 2026"

format:
  html:
    theme: 
      light: [journal, web_styles.scss]
    toc: true
    mainfont: "Fredoka"
    
execute:
  freeze: auto
